import getPages from "@/lib/getPages";
import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pages = await getPages();
  return (
    <html lang="de">
      <body>
        <nav>
          {pages.map((page)=><Link key={page.id} href={`/${page.id}`}>{page.Title}</Link>)}
        </nav>
        <main>
          {children}
        </main>
      </body>
    </html>
  );
}
